// Release safety guards (Phase 4 §1). The single most important property of a public package is that
// installing it is INERT — `npm install -g corpocode` must only place the binary on the path, never
// register hooks, provision daemons, write config, or touch the network. That property is enforced by
// the ABSENCE of install lifecycle scripts and by a tight files allowlist, both asserted here so a
// future edit can't reintroduce a surprising install-time side effect without a red test.
import { describe, it, expect } from "vitest";
import { readFileSync } from "node:fs";
import { join } from "node:path";

const pkg = JSON.parse(readFileSync(join(__dirname, "..", "..", "package.json"), "utf8"));

describe("packaging is inert and minimal", () => {
  it("declares no install lifecycle scripts (install must do nothing but place the binary)", () => {
    for (const hook of ["preinstall", "install", "postinstall"]) {
      expect(pkg.scripts?.[hook]).toBeUndefined();
    }
  });

  it("ships only the bundled binary and assets — never src or tests", () => {
    expect(pkg.files).toContain("bin");
    expect(pkg.files).not.toContain("src");
    expect(pkg.files).not.toContain("tests");
    // The bin is a single bundled file, so no node_modules resolution happens at runtime either.
    expect(pkg.bin.corpocode).toBe("./bin/corpocode.js");
  });

  it("pins a Node floor and publishes publicly", () => {
    expect(pkg.engines.node).toBe(">=20");
    expect(pkg.publishConfig?.access).toBe("public");
    // Provenance is generated by the CI release workflow (NPM_CONFIG_PROVENANCE), not publishConfig —
    // a manual `npm publish` from a laptop can't produce OIDC provenance, so it must not be forced here.
    expect(pkg.publishConfig?.provenance).toBeUndefined();
    expect(pkg.repository?.url).toMatch(/github\.com/); // a real repository URL for the package page
  });
});
