// Provision OpenViking: generate ov.conf from CorpoCode's own provider config (so the user
// authenticates once and OpenViking inherits the same model/key), install the daemon if absent,
// start it, and wait for health. Phase 1 provisions OpenViking even though its adapter isn't wired
// into a hook until Phase 2 — that completes the operational picture and lets doctor verify it.
import { writeFileSync } from "node:fs";
import { homedir } from "node:os";
import { dirname, join } from "node:path";
import type { CorpoConfig, ProviderKind } from "../../config/schema";
import { ensureDir } from "../../config/paths";
import { buildContextStore } from "../../backends/context/registry";
import type { ContextStore } from "../../backends/context/types";
import type { CommandRunner, ProvisionResult, ProvisionStep } from "../run";
import { spawnRunner } from "../run";

export function ovConfPath(env: NodeJS.ProcessEnv = process.env): string {
  return env.OPENVIKING_CONFIG ?? join(homedir(), ".openviking", "ov.conf");
}

interface EmbeddingChoice {
  provider: string;
  model: string;
}

// A sensible embedding pairing per provider kind. Anthropic has no embeddings API, so we default
// it to a local, keyless Ollama embedder rather than forcing a second credential.
function embeddingFor(kind: ProviderKind): EmbeddingChoice {
  switch (kind) {
    case "openai":
    case "openrouter":
      return { provider: "openai", model: "text-embedding-3-small" };
    case "google":
      return { provider: "gemini", model: "text-embedding-004" };
    case "ollama":
    case "anthropic":
    case "anthropic-cli":
      return { provider: "ollama", model: "nomic-embed-text" };
    default: {
      const unreachable: never = kind;
      throw new Error(`unsupported provider kind: ${String(unreachable)}`);
    }
  }
}

/** Generate ov.conf content from the configured provider. Pure and unit-testable. */
export function generateOvConf(
  config: CorpoConfig,
  opts: { providerKey?: string; apiKey?: string } = {},
): string {
  const key = opts.providerKey ?? config.components.retrieval;
  const provider = config.providers[key] ?? config.providers.default!;
  const embedding = embeddingFor(provider.kind);
  const apiKeyLine = opts.apiKey ? `api_key = "${opts.apiKey}"` : `# api_key resolved from environment`;
  return [
    "# Generated by `corpocode install`/`--repair`. OpenViking inherits CorpoCode's provider.",
    "[llm]",
    `provider = "${provider.kind}"`,
    `model = "${provider.model}"`,
    apiKeyLine,
    "",
    "[embedding]",
    `provider = "${embedding.provider}"`,
    `model = "${embedding.model}"`,
    "",
  ].join("\n");
}

export interface OpenVikingProvisionOptions {
  config: CorpoConfig;
  apiKey?: string;
  store?: ContextStore;
  run?: CommandRunner;
  writeConf?: (path: string, content: string) => void;
  confPath?: string;
  dryRun?: boolean;
}

export async function provisionOpenViking(opts: OpenVikingProvisionOptions): Promise<ProvisionResult> {
  const run = opts.run ?? spawnRunner;
  const store = opts.store ?? buildContextStore(opts.config);
  const confPath = opts.confPath ?? ovConfPath();
  const writeConf =
    opts.writeConf ??
    ((path: string, content: string) => {
      ensureDir(dirname(path));
      writeFileSync(path, content);
    });
  const steps: ProvisionStep[] = [];

  if (opts.dryRun) {
    return {
      component: "openviking",
      ok: true,
      steps: [
        { name: "write ov.conf", ok: true, detail: confPath, skipped: true },
        { name: "install openviking", ok: true, detail: "pip install openviking (if missing)", skipped: true },
        { name: "start daemon", ok: true, detail: "openviking-server", skipped: true },
        { name: "health check", ok: true, detail: "GET /health", skipped: true },
      ],
    };
  }

  writeConf(confPath, generateOvConf(opts.config, { apiKey: opts.apiKey }));
  steps.push({ name: "write ov.conf", ok: true, detail: confPath });

  const ver = await run("openviking-server", ["--version"]);
  if (ver.code !== 0) {
    const install = await run("python", ["-m", "pip", "install", "--quiet", "openviking"]);
    steps.push({ name: "install openviking", ok: install.code === 0, detail: install.code === 0 ? "installed" : install.stderr.trim() });
  } else {
    steps.push({ name: "openviking present", ok: true, detail: ver.stdout.trim() });
  }

  try {
    await store.start();
    steps.push({ name: "start daemon", ok: true, detail: "started" });
  } catch (err) {
    steps.push({ name: "start daemon", ok: false, detail: err instanceof Error ? err.message : String(err) });
  }

  const health = await store.health();
  steps.push({ name: "health check", ok: health.up, detail: health.up ? `up${health.version ? ` (${health.version})` : ""}` : "unreachable" });

  return { component: "openviking", ok: steps.every((s) => s.ok), steps };
}
